FROM golang as binstage
COPY ./runforever.go /go/runforever.go
RUN \
 GOOS=linux GOARCH=arm \
 go build -ldflags="-w -s" -o /runforever
FROM scratch
COPY --from=binstage /runforever /runforever
ENTRYPOINT ["/runforever"]
